### ISSUE TITLE
reset loop issue

### ISSUE THREAD

**Issue by mukil-bluerider** [Suraj151/esp8266-framework#1]
hi,
i used your library and flashed "**Nodemcu v1.0**" board using **Arduino IDE 1.8.12**.
the flash is success but the module keeps on restarting and AP WiFi is not showing in wifi scan.

please let me know what is the issue and please provide any documentation.

**Comment by Suraj151** [comment]
@mukil-bluerider thank you for reach
before i can got further can i know which arduino-esp8266 version of release you are using ?
and did you follow this

> for now : if you are uploading it first time in device then wait for 5 seconds(default station connect timeout on start) and then press flash key on nodemcu board for upto 6-7 seconds to load first default settings. device will get reset to default settings and restart.

also try with erase all content while uploading. option available in arduino ide tool

sorry if brief documentation is not enough but will update it step by step it just recently push work

**Comment by mamanbudiman** [comment]
Hello,
 Yes, I found the reset loop issue,

This is in the serial monitor `Initializing...

Connecing To esp8266Stack.....
WiFi Not Connecting. Will try later soon..
Configuring access point esp8266Stack ..
AP IP address: 192.168.123.1
HTTP server started
Flash Key pressed : 1
Flash Key pressed : 2
Flash Key pressed : 3
Flash Key pressed : 4

WiFi Configs :
esp8266Stack	espStack@8266	0.0.0.0	0.0.0.0	0.0.0.0	

Access Configs :
esp8266Stack	espStack@8266	192.168.123.1	192.168.123.1	255.255.255.0	


OTA Configs :
	80


GPIO Configs (mode) :
0	0	0	0	0	0	0	0	0	0	
GPIO Configs (readings) :
0	0	0	0	0	0	0	0	0	0	
GPIO Configs (alert comparator) :
0	0	0	0	0	0	0	0	0	0	
GPIO Configs (alert channels) :
0	0	0	0	0	0	0	0	0	0	
GPIO Configs (alert values) :
0	0	0	0	0	0	0	0	0	0	
GPIO Configs (server) :
	80	5


Mqtt General Configs :
	1883	0				120	1

Mqtt Lwt Configs :
		0	0

Mqtt Pub Configs :

Mqtt Sub Configs :

Email Configs :
www.example.com	smtp.mailtrap.io	2525	sdc10dfgdf326d	zdvfvfdvddfvfd	
surajinamdar151@gmail.com	esp8266	surajinamdar151@gmail.com	device status	300

Tasks : 
id	priority	duration	last_ms		execute_ms	max_attempts
1	0		10000		7384		0		-1
2	0		15000		7388		0		-1
3	0		1000		11392		0		-1
4	0		300000		7388		0		-1
5	0		5000		12390		0		0
6	0		120000		0		0		-1
7	0		5000		7389		0		-1
8	0		1000		11393		0		-1

NTP Validity : 0
NTP Time : 28812
Flash Key pressed : 5
Flash Key pressed : 6
requested factory reset !

 ets Jan  8 2013,rst cause:2, boot mode:(3,0)

load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
Initializing...

Connecing To esp8266Stack.....
WiFi Not Connecting. Will try later soon..
Configuring access point esp8266Stack ..
AP IP address: 192.168.123.1
HTTP server started
Flash Key pressed : 1

`

I use Nodemcu, and the latest arduino-esp8266

As you can see, esp8266 restart the operation.

**Comment by mukil-bluerider** [comment]
Hi suraj,
i'm so so sorry for a so late response.
you are awesome, have done a really great job.
i used version 1.1.0 for my module.
i followed the above mentioned procedure and it worked charmingly. 
i used "v2 lower memory" lwip in the build.
thank you so much.

Also i did go through the settings. 
may i request if it is possible to add a feature to connect to exiting OPEN wifi network or plz let me know if this feature exist already.

Again thank you so much.
Happy day.

**Comment by Suraj151** [comment]
@mukil-bluerider Glad to here that it helps to you!

There are many features available in architecture which can be enabled through configuration files (under config folder)

Actually the pain point of this architecture is documentation ( and thats what i am currently planning to wrap up as early as possible in simple ways )

feature of connecting to open network is not planned in current framework but sure it can be easily made available with next release.

priority is on documentation now which i will update to wiki of this repo whenever i get enough time

Thank you for your interest and suggestions !

**Comment by mukil-bluerider** [comment]
Hi again suraj,
for the previous request i have given.
i have made some modifications in header to support the feature.
-----Connecting to Open WiFi network------
mod1: 
i have changed value from 3 to 0 in Line 30: #define MIN_ACCEPTED_ARG_SIZE 0 in file
*esp8266-framework\src\webserver\resources\WebResource.h
mod2:
i have changed in file *\esp8266-framework\src\webserver\controllers\WiFiConfigController.h
as  _sta_ssid.length() > MIN_ACCEPTED_ARG_SIZE && _sta_pswd.length() >= MIN_ACCEPTED_ARG_SIZE && in Line 184:

**Comment by Suraj151** [comment]
@mukil-bluerider great !
will plan to make suggested changes in next release !
