### ISSUE TITLE
scanNetwork

### ISSUE THREAD

**Issue by Lastiottech** [Suraj151/esp8266-framework#10]
hi bro i hope you are well :)

On the "WifiConfigPage.h" page

G:17 = WiFi Configuration

to the bottom line

"https://theiotprojects.com/esp8266-manual-wifi-configuration-with-eeprom-without-hard-code/#source-codeprogram"

"WiFi.scanNetworks();" in this link I wanted to add the function, although it is defined on WifiInterface.h, I could not succeed, your functions are really perfect.

Is there any way I can do this?

**Comment by Suraj151** [comment]
Hi @Lastiottech 

I don't understood your query
