### ISSUE TITLE
cannot finish the EWstack.INO

### ISSUE THREAD

**Issue by renshaozhang** [Suraj151/esp8266-framework#11]
hello suraj
 i have open the example ewstack.ino,and upload ,but cannot do compile.
there are many warning.the bottom lists some ,can you tell me how to fix it.thank you very much.
C:\Users\lenovo\Documents\Arduino\libraries\esp8266-framework\src/webserver/helpers/HtmlTagsAndAttr.h:83:47: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   83 | #define HTML_INPUT_CHECKBOX_TAG_TYPE          "checkbox"
      |                                               ^~~~~~~~~~
C:\Users\lenovo\Documents\Arduino\libraries\esp8266-framework\src/webserver/controllers/EmailConfigController.h:92:121: note: in expansion of macro 'HTML_INPUT_CHECKBOX_TAG_TYPE'
   92 |    concat_tr_input_html_tags( _page, PSTR("Send Test Mail ?"), PSTR("tstml"), "test", HTML_INPUT_TAG_DEFAULT_MAXLENGTH, HTML_INPUT_CHECKBOX_TAG_TYPE, false );
      |                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\lenovo\Documents\Arduino\libraries\esp8266-framework\src\EwingsEspStack.cpp: In member function 'void EwingsEspStack::enable_napt_service()':
C:\Users\lenovo\Documents\Arduino\libraries\esp8266-framework\src\EwingsEspStack.cpp:121:7: error: 'dhcpSoftAP' was not declared in this scope
  121 |       dhcpSoftAP.dhcps_set_dns(0, this->m_wifi->dnsIP(0));
      |       ^~~~~~~~~~
Using library esp8266-framework at version 1.1.5 in folder: C:\Users\lenovo\Documents\Arduino\libraries\esp8266-framework 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\ESP8266WiFi 
Using library ESP8266HTTPClient at version 1.2 in folder: C:\Users\lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\ESP8266HTTPClient 
Using library ESP8266WebServer at version 1.0 in folder: C:\Users\lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\ESP8266WebServer 
Using library Ticker at version 1.0 in folder: C:\Users\lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\Ticker 
Using library ESP8266httpUpdate at version 1.3 in folder: C:\Users\lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\ESP8266httpUpdate 
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by Suraj151** [comment]
Hi @renshaozhang 

from your logs it seems that you are using latest esp8266 lib version. in usage section i suggested to use esp8266 version > 3.0.x. i.e. 3.0.2 or greater patch version.

since this library is worked and tested upto arduino esp8266 version 3.0.x, i suggest to please install 3.0.2 version and try. since latest arduino esp8266 version i.e. 3.1.2 has many breaking changes, which is not yet supported on this library.

Thanks for your notice, i will check to update this library to support latest arduino esp8266 version in upcoming days

**Comment by renshaozhang** [comment]
Thank you very much,i changed ESP8266 3.0.2,It can work .
