### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by sdp74** [Suraj151/esp8266-framework#2]
In file included
from  \Arduino\libraries\esp8266-framework\src/config/Config.h:13:0,
from  \Arduino\libraries\esp8266-framework\src\utility\FactoryReset.h:15,
from  \Arduino\libraries\esp8266-framework\src\utility\FactoryReset.cpp:10:

\Arduino\libraries\esp8266-framework\src\utility\FactoryReset.cpp: In member function 'void DeviceFactoryReset::handleFlashKeyPress()':
\Arduino\libraries\esp8266-framework\src/config/Common.h:79:35: error: 'D3' was not declared in this scope
 #define FLASH_KEY_PIN             D3
                                   ^
\Arduino\libraries\esp8266-framework\src\utility\FactoryReset.cpp:64:19: note: in expansion of macro 'FLASH_KEY_PIN'
   if( digitalRead(FLASH_KEY_PIN) == LOW ){
                   ^
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by Suraj151** [comment]
@sdp74 
Error is about D3 declaration. it is board specific. this pin is defined in **NodeMCU 1.0** board. please select board **NodeMCU 1.0** and try again

**Comment by sdp74** [comment]
Indeed with **NodeMCU 1.0** board the compiling process works. But I have 1 Sonoff Basic with only 1MB Flash: no way to flash it via Arduino IDE correctly.

**Comment by Suraj151** [comment]
@sdp74 I think it need custom flash 
You can refer https://medium.com/@jeffreyroshan/flashing-a-custom-firmware-to-sonoff-wifi-switch-with-arduino-ide-402e5a2f77b
Check whether you can flash it with available header pins on board as suggested in above link

**Comment by sdp74** [comment]
I have no problem flashing my Sonoff (i have several with Tasmota firmware). The point is the Arduino IDE when you choose NODEMCU 1.0 you have 4 flash options that are mainly incompatible with a device with only 1 MB Flash like a generic ESP8266.
![FlashOptions](https://user-images.githubusercontent.com/67475197/85921652-ddcf6200-b87d-11ea-816a-c772f1f94c9b.jpg)

**Comment by Suraj151** [comment]
@sdp74 ohhk... then replace D3 defination with actual gpio pin no. I think gpio 0 is mapped to D3 in nodemcu... So instead of
#define FLASH_KEY_PIN D3
Write it as
#define FLASH_KEY_PIN 0
In Common.h config header file

Make sure that gpio 0 pin should not be digital low or else reset factory loop will start.

**Comment by sdp74** [comment]
Gpio0 on the Sonoff is connected to a push button, and it is used also for the flashing mode (power on + push button). I suppose that is the normal way to act for ESP8266 based board. I will try to modify the source code and then i will let you know.

**Comment by sdp74** [comment]
Thanks: it is ok. I read that is also possible to get a NATP functionality lwip 1.4. After changing the library will I found others parameters (fields) on the wifi section of the http page?

**Comment by Suraj151** [comment]
Yes sure.... Currently it's not added to control from browser portal.... It should be done before compiling.... If you want then you can modify it whether to keep or not napt feature before compiling.... 
But napt can be possible to configure from browser...

**Comment by sdp74** [comment]
OK. But i cannot find where? Can you give me a tip? ;)

**Comment by Suraj151** [comment]
@sdp74 to get it done by browser you have to make controller and http page for the same.... In initialization of stack you will find napt_init function ... Just enable or disable this function from portal...  For that You need to make one table regarding napt configs.... Access it from web controller in framework... 
I can't explain the whole thing... But it should be in this way to make available this functionality from browser portal...

**Comment by sdp74** [comment]
Ok. So it not at the moment implemented in the webserver. Ok i see that you use an MVC approach. Maybe in the future i will try to implement it. Do you use IDF from espressif? Do you use some framework/ide? 

Thanks for your patience and collaboration.
