### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by ShikOfTheRa** [Suraj151/esp8266-framework#8]
Hi - your library looks mighty impressive !!! Thank you for your time to release into public for us

I have an error compiling the ewings example: any suggestions?

In file included from C:\Users\xx\Documents\Arduino\libraries\esp8266-framework\src/interface/WiFiClientInterface.h:14,
                 from C:\Users\xx\Documents\Arduino\libraries\esp8266-framework\src/EwingsEspStack.h:17,
                 from C:\Users\xx\Documents\Arduino\sketch_jul07a\sketch_jul07a.ino:6:
C:\Users\xx\Documents\Arduino\libraries\esp8266-framework\src/interface/iWiFiClientInterface.h:60:20: error: conflicting return type specified for 'virtual size_t iWiFiClientInterface::availableForWrite()'
   60 |     virtual size_t availableForWrite() = 0;
      |                    ^~~~~~~~~~~~~~~~~
In file included from C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Stream.h:27,
                 from C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/HardwareSerial.h:32,
                 from C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Arduino.h:288,
                 from C:\Users\GARY_M~1\AppData\Local\Temp\arduino_build_645607\sketch\sketch_jul07a.ino.cpp:1:
C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\cores\esp8266/Print.h:80:21: note: overridden function is 'virtual int Print::availableForWrite()'
   80 |         virtual int availableForWrite() { return 0; }
      |                     ^~~~~~~~~~~~~~~~~

**Comment by Suraj151** [comment]
Which Arduino esp8266 release version you are using..

**Comment by ShikOfTheRa** [comment]
Arduino 1.8.15 (Windows Store 1.8..49.0)
Using library esp8266-framework at version 1.1.4 in folder: C:\Users\xx\Documents\Arduino\libraries\esp8266-framework 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266WiFi 
Using library ESP8266HTTPClient at version 1.2 in folder: C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266HTTPClient 
Using library ESP8266WebServer at version 1.0 in folder: C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266WebServer 
Using library ESP8266httpUpdate at version 1.3 in folder: C:\Users\xx\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.0\libraries\ESP8266httpUpdate

Gary Moscardini

**Comment by Suraj151** [comment]
@ShikOfTheRa please debug and check the below link as some change has been happened which breaks the older api's

https://github.com/esp8266/Arduino/commit/7f38e141c7502032af594fdd502c1b1f6049377c#diff-5a9949c745776a63a14b971326149d4db7e7200d78ed56dfcacedda31de4f875

Make 
size_t iWiFiClientInterface::availableForWrite();
Api return type as int as per above link.

I will update once I back to my work space

**Comment by Suraj151** [comment]
@ShikOfTheRa 
i have updated latest release, so closing this one
