### ISSUE TITLE
Hi, Gpio Control is not possible by Mqtt?

### ISSUE THREAD

**Issue by Lastiottech** [Suraj151/esp8266-framework#9]
ino file
void subscribe_callback( uint32_t *args, const char* topic, uint32_t topic_len, const char *data, uint32_t data_len ){

I really messed with it, but when I turned on the led with mqtt, I was not able to send the status information to the broker.

**Comment by Suraj151** [comment]
the example shows about publish callback and subscribe data callback. 

Can you give me some idea on how you are using this example with your application ?

i mean how you are turning on led and where you are sending status information to server

you can refer 
https://github.com/Suraj151/esp8266-framework/wiki/GPIO-Service
to use gpio control/monitor over mqtt. its by default enabled feature in framework.

**Comment by Lastiottech** [comment]
{
 "data":{
  "D0":{
   "mode":0,
   "val":0
  },
  "D1":{
   "mode":1,
   "val":1
  },
  "D2":{
   "mode":0,
   "val":0
  },
  "D4":{
   "mode":0,
   "val":0
  },
  "D5":{
   "mode":0,
   "val":0
  },
  "D6":{
   "mode":0,
   "val":0
  },
  "D7":{
   "mode":0,
   "val":0
  },
  "D8":{
   "mode":0,
   "val":0
  },
  "A0":{
   "mode":0,
   "val":0
  }
 }
}


yes.ok, this was successful, I have read all the pages except this page, thank you for your effort, you have done a nice work bro.

If I succeed in the short-term opening and closing part, I will be happy :)

**Comment by Lastiottech** [comment]
GpioServiceProvider.cpp

217 ->

      case DIGITAL_WRITE:{
        // Log( F("writing "));Log( this->getGpioFromPinMap( _pin ) );Log( F(" pin to "));Logln( this->m_gpio_config_copy.gpio_readings[_pin]);
        digitalWrite( this->getGpioFromPinMap( _pin ), this->m_gpio_config_copy.gpio_readings[_pin] );
		delay(200);
        digitalWrite( this->getGpioFromPinMap( _pin ), HIGH );
		delay(200);
		digitalWrite( this->getGpioFromPinMap( _pin ), this->m_gpio_config_copy.gpio_readings[_pin] );
		delay(200);
		digitalWrite( this->getGpioFromPinMap( _pin ), HIGH );
	while(1)
        break;
      }

I think I've solved the problem for now :)

**Comment by Suraj151** [comment]
@Lastiottech good to know that you got some tweaks for now..
Currently I am out of my workspace reach.. so unable to update.
Will update once I reach my workspace..

Just give me any suggestion that you faced and solved.. I will check if I can make it better than current

**Comment by Lastiottech** [comment]
My suggestion is my dear brother,
Having the pin controls always off or on will not always work. So I temporarily used the suggestion I gave above.

My suggestion is:
enum GPIO_MODE {
   OFF=0,
   DIGITAL_WRITE=1,
   DIGITAL_READ=2,
   ANALOG_WRITE=3,
   ANALOG_READ=4
};
  TO
enum GPIO_MODE {
   OFF=0,
   DIGITAL_WRITE=1,
   DIGITAL_READ=2,
   ANALOG_WRITE=3,
   ANALOG_READ=4
   BLINK_WRITE=5
   BLINK_WRITE_2=6
};

When there is the blink write part,

The button that stays open for the duration of the value and then closes is not always open :)

When blink_write_2 turns it on and off twice in a row, etc. I think it will help us to control the on/off times of the relay or pin.

**Comment by Suraj151** [comment]
@Lastiottech 
i have updated release 1.1.5 with your suggested blink feature. now we can blink any digital pin with provided duration for it.
thanks for that suggestion
